# Generated by Django 3.1.6 on 2021-11-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_follow_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
